name: npm test

on: [push]

jobs:

  test:

    runs-on: ubuntu-latest

    strategy:

      matrix:

        node_version: [21.x]

    steps:

      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}

        uses: actions/setup-node@v1

        with:

          node-version: ${{ matrix.node-version }}

      - run: npm i node-fetch@2.6.1

      - run: npm install

      - run: npm install mocha chai

      - run: npm run build --if-present

      - run: npx mocha test/test.js
